### ISSUE TITLE
Esim

### ISSUE THREAD

**Issue by zohreh3906** [Deep1994/ESIM-keras#1]
Hello 
Is there a reliable code?

 Has an article referenced this code?

**Comment by HelloDeep** [comment]
Hi, sorry for the late reply.  I mainly reffer to [https://www.kaggle.com/lamdang/dl-models](https://www.kaggle.com/lamdang/dl-models)，who was the 1st of the kaggle Quora Question Pairs competition，and I think it is a reliable code. So far, there is no article citing this code, if you have any questions, please let me know.

best wish
Deep1994

**Comment by Deep1994** [comment]
Hi, sorry for the late reply. I mainly reffer to https://www.kaggle.com/lamdang/dl-models，who was the 1st of the kaggle Quora Question Pairs competition，and I think it is a reliable code. So far, there is no article citing this code, if you have any questions, please let me know.

best wish
Deep1994

**Comment by Deep1994** [comment]
Hi, sorry for the late reply. I mainly reffer to [https://www.kaggle.com/lamdang/dl-models](https://www.kaggle.com/lamdang/dl-models)，who was the 1st of the kaggle Quora Question Pairs competition，and I think it is a reliable code. So far, there is no article citing this code, if you have any questions, please let me know.

best wish
Deep1994
